name: ATH Updater

on:
  workflow_dispatch:

  schedule:
    - cron: '0 15 27 * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: |
          python ath_update.py
